[project]
name = "batchobf"
version = "0.1.0"
description = "BatchOBF is a Python obfuscation tool designed to make batch files harder to understand for casual users."
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[tool.poetry]
package-mode = false
